### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Hachiman2810** [TeraProxy/Cosplayer#12]
When you start the proxy for the first time and enter the game, the module starts normally, in some case you return to the server list and select the same or other server the module shows an error, this also happens when you close the game and open it again (without closing/restart proxy).

![proxy2](https://user-images.githubusercontent.com/40275707/41812448-7b0399b2-76e8-11e8-9781-b567f1421664.png)

**Comment by DU1R** [comment]
Can confirm the same thing happens to me with this module when server disconnects. All other installed modules load fine. Have to close TERA and TeraProxy and relaunch both to restore.

```
[23:49:41 GMT-0700] ERROR tera-proxy-game: [dispatch] load: error initializing module "cosplayer"
error: Module did not self-register.
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:731:18)
    at Module.load (internal/modules/cjs/loader.js:612:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:551:12)
    at Function.Module._load (internal/modules/cjs/loader.js:543:3)
    at Module.require (internal/modules/cjs/loader.js:650:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at bindings (C:\TrustedSpace\CaaliTeraProxy\bin\node_modules\cosplayer\node_modules\bindings\bindings.js:81:44)
    at Object.<anonymous> (C:\TrustedSpace\CaaliTeraProxy\bin\node_modules\cosplayer\node_modules\win-mouse\index.js:3:13)
```

**Comment by TeraProxy** [comment]
Yeah, that's a know problem with the module caching feature of the current tera-proxy. You'll have to restart the proxy when you disconnect or disable module caching. I still didn't manage to get behind this but assume it's related to using a c++ dependency.

**Comment by TeraProxy** [comment]
I finally fixed this issue. If anyone with a similar problem might need it, this is what's actually happening: https://github.com/nodejs/node/issues/6160

Solution is to make native c++ addons not unload by declaring them globally. I'll push the update soon.
