### ISSUE TITLE
idk what is going on 

### ISSUE THREAD

**Issue by begamerbr** [TeraProxy/Cosplayer#15]
DeprecationWarning: Long.JS is deprecated. Use BigInt equivalents instead.
    at Object.Cosplayer.dispatch.hook.event [as callback] (C:\Users\User\Desktop\tera-proxy\bin\node_modules\Cosplayer-master\index.js:156:19)

showing this message when log in in my char ;-;

**Comment by TeraProxy** [comment]
@begamerbr It is because Pinkie Pie updated his proxy to use a new feature of current NodeJS versions instead of a workaround we used before.

This is just a warning and will not cause you any harm. Cosplayer will still work normally. I'm going to update to bigInt very soon which will also get rid of this warning message. Don't worry, you are fine!

**Comment by begamerbr** [comment]
oh, ty for your answer, but when i try to change to any outfit, show a message and i got disconnected.

**Comment by begamerbr** [comment]
TypeError: Do not know how to serialize a BigInt
    at JSON.stringify (<anonymous>)
    at Timeout.presetSave [as _onTimeout] (C:\Users\User\Desktop\tera-proxy\bin\node_modules\Cosplayer-master\index.js:75:59)
    at ontimeout (timers.js:427:11)
    at tryOnTimeout (timers.js:289:5)
    at listOnTimeout (timers.js:252:5)
    at Timer.processTimers (timers.js:212:10)
Pressione qualquer tecla para continuar. . .

**Comment by begamerbr** [comment]
![image](https://user-images.githubusercontent.com/40698997/42126794-afb0c40c-7c63-11e8-9424-8a22ac3ac1b1.png)

**Comment by TeraProxy** [comment]
Glad to hear, this Dureal guy must be an awesome dude! :)
