### ISSUE TITLE
cosplayer not working

### ISSUE THREAD

**Issue by misslunaaa** [TeraProxy/Cosplayer#35]
23:45:28.988] [31mERROR [0mYour current Node.JS version (Electron version: 8.1.0) is not compatible with Cosplayer. Please go here for advice:
[36mhttps://github.com/TeraProxy/Cosplayer/wiki/Version-Incompatibility[0m
[23:45:29.021] [mods] ERROR: Module "Cosplay" (Cosplayer) could not be loaded!
[23:45:29.021] [mods] ERROR: Please contact the module's author: https://github.com/TeraProxy/Cosplayer/issues
[23:45:29.022] TypeError: Mouse is not a constructor
    at EventEmitter.<anonymous> (E:\TeraToolbox\mods\Cosplayer\mouse.js:57:11)
    at Object.onceWrapper (events.js:300:26)
    at EventEmitter.emit (events.js:210:5)
    at _addListener (events.js:236:14)
    at EventEmitter.addListener (events.js:284:10)
    at new Cosplayer (E:\TeraToolbox\mods\Cosplayer\index.js:46:8)
    at ModuleManager.load (E:\TeraToolbox\node_modules\tera-network-proxy\lib\connection\dispatch\moduleManager.js:157:35)
    at E:\TeraToolbox\node_modules\tera-network-proxy\lib\connection\dispatch\moduleManager.js:122:22
    at Map.forEach (<anonymous>)
    at ModuleManager.loadAll (E:\TeraToolbox\node_modules\tera-network-proxy\lib\connection\dispatch\moduleManager.js:120:31)

**Comment by jisn064** [comment]
I've the same error.
`[19:57:30.759] [31mERROR [0mYour current Node.JS version (Electron version: 8.1.0) is not compatible with Cosplayer. Please go here for advice:
[36mhttps://github.com/TeraProxy/Cosplayer/wiki/Version-Incompatibility[0m
[19:57:30.836] [mods] ERROR: Module "Cosplay" (Cosplayer) could not be loaded!
[19:57:30.837] [mods] ERROR: Please contact the module's author: https://github.com/TeraProxy/Cosplayer/issues
[19:57:30.839] TypeError: Mouse is not a constructor
    at EventEmitter.<anonymous> (C:\Users\USUARIO\AppData\Local\Programs\TeraToolbox\mods\Cosplayer-master\mouse.js:57:11)
    at Object.onceWrapper (events.js:300:26)
    at EventEmitter.emit (events.js:210:5)
    at _addListener (events.js:236:14)
    at EventEmitter.addListener (events.js:284:10)
    at new Cosplayer (C:\Users\USUARIO\AppData\Local\Programs\TeraToolbox\mods\Cosplayer-master\index.js:46:8)
    at ModuleManager.load (C:\Users\USUARIO\AppData\Local\Programs\TeraToolbox\node_modules\tera-network-proxy\lib\connection\dispatch\moduleManager.js:157:35)
    at C:\Users\USUARIO\AppData\Local\Programs\TeraToolbox\node_modules\tera-network-proxy\lib\connection\dispatch\moduleManager.js:122:22
    at Map.forEach (<anonymous>)
    at ModuleManager.loadAll (C:\Users\USUARIO\AppData\Local\Programs\TeraToolbox\node_modules\tera-network-proxy\lib\connection\dispatch\moduleManager.js:120:31)`

**Comment by Gretaf888** [comment]
Та же проблема( решите пожалуйста!

**Comment by Gretaf888** [comment]
Только электронная версия 8.2.2.
